# Generated by Django 4.1.6 on 2024-08-29 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0002_proformainvoice_prospective_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdeals',
            name='model',
        ),
        migrations.RemoveField(
            model_name='salesdeals',
            name='stock_type',
        ),
        migrations.AlterField(
            model_name='salesdeals',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.carmodel'),
        ),
    ]
