# Generated by Django 4.1.6 on 2024-09-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0004_jobcard_jobcardimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
