# Generated by Django 4.1.6 on 2024-09-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0006_jobcardtransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='mechanic',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='wr_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
