# Generated by Django 4.1.6 on 2024-09-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0007_jobcard_mechanic_jobcard_wr_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='close_remark',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcard',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
    ]
