# Generated by Django 4.1.6 on 2024-09-13 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmms', '0008_jobcard_close_remark_jobcard_is_ended'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=65)),
                ('reason', models.TextField(max_length=25000)),
                ('requested_on', models.DateField(auto_now_add=True)),
                ('is_issued', models.BooleanField(default=False)),
                ('issued_on', models.DateField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_by', to=settings.AUTH_USER_MODEL)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.jobcard')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
