# Generated by Django 4.1.6 on 2024-09-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0009_jobmaterials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcardimages',
            name='image',
            field=models.ImageField(upload_to='static/uploads/job_check_lists'),
        ),
    ]
