# Generated by Django 4.1.6 on 2024-09-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0010_alter_jobcardimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmaterials',
            name='part',
            field=models.CharField(max_length=255),
        ),
    ]
