# Generated by Django 4.1.6 on 2024-09-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0011_alter_jobmaterials_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmaterials',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobmaterials',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
