# Generated by Django 4.1.6 on 2024-09-20 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0013_alter_jobcard_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2024, 9, 20, 10, 9, 35, 496496, tzinfo=datetime.timezone.utc)),
        ),
    ]
