# Generated by Django 4.1.6 on 2024-09-20 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0014_alter_jobcard_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
