# Generated by Django 4.1.6 on 2024-09-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0015_alter_jobcard_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='next_service_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
