# Generated by Django 4.1.6 on 2024-09-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0016_jobcard_next_service_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcardimages',
            name='image',
            field=models.ImageField(upload_to="upload_to='static/uploads/dolphine/servicing/%Y/%m/%d/'"),
        ),
    ]
