# Generated by Django 4.1.6 on 2024-09-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0017_alter_jobcardimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcardimages',
            name='image',
            field=models.ImageField(upload_to='static/uploads/dolphine/servicing//%Y/%m/%d/'),
        ),
    ]
