# Generated by Django 4.1.6 on 2024-07-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolphine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
