# Generated by Django 4.1.6 on 2024-09-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dolphine', '0002_documents_description_documents_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file',
        ),
    ]
