# Generated by Django 4.1.6 on 2024-07-13 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_bulksms_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulksms',
            name='file',
            field=models.FileField(upload_to='static/uploads/bsms/2024-07-13_13-08-03'),
        ),
        migrations.AlterField(
            model_name='transferhd',
            name='loc_fr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_location_from', to='admin_panel.locations'),
        ),
        migrations.AlterField(
            model_name='transferhd',
            name='loc_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_location_to', to='admin_panel.locations'),
        ),
    ]
