# Generated by Django 4.1.6 on 2024-07-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_bulksms_file_alter_transferhd_loc_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferhd',
            name='entry_no',
            field=models.CharField(max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bulksms',
            name='file',
            field=models.FileField(upload_to='static/uploads/bsms/2024-07-13_13-09-45'),
        ),
    ]
