# Generated by Django 4.1.6 on 2024-07-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_transferhd_entry_no_alter_bulksms_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfertran',
            old_name='total',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='transfertran',
            old_name='quantity',
            new_name='tran_qty',
        ),
        migrations.AddField(
            model_name='transfertran',
            name='pack_qty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=65),
        ),
        migrations.AddField(
            model_name='transfertran',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=65),
        ),
        migrations.AlterField(
            model_name='bulksms',
            name='file',
            field=models.FileField(upload_to='static/uploads/bsms/2024-07-13_13-15-33'),
        ),
    ]
