# Generated by Django 4.1.6 on 2024-07-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_rename_total_transfertran_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferhd',
            old_name='remark',
            new_name='remarks',
        ),
        migrations.AlterField(
            model_name='bulksms',
            name='file',
            field=models.FileField(upload_to='static/uploads/bsms/2024-07-13_13-21-59'),
        ),
    ]
