# Generated by Django 4.1.6 on 2024-07-13 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0010_rename_remark_transferhd_remarks_alter_bulksms_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulksms',
            name='file',
            field=models.FileField(upload_to='static/uploads/bsms/2024-07-13_13-23-37'),
        ),
        migrations.AlterField(
            model_name='transferhd',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_hd_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
