# Generated by Django 4.1.6 on 2024-07-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_alter_bulksms_file_alter_transferhd_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulksms',
            name='file',
            field=models.FileField(upload_to='static/uploads/bsms/2024-07-13_13-30-47'),
        ),
        migrations.AlterField(
            model_name='transfertran',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=65),
        ),
    ]
