# Generated by Django 4.1.6 on 2024-07-26 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0013_alter_bulksms_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.useraddons'),
        ),
        migrations.AddField(
            model_name='transferhd',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferhd',
            name='delivery_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transferhd',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transferhd',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transferhd',
            name='rec_remark',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transferhd',
            name='reccieved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_recieved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferhd',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_sent_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bulksms',
            name='file',
            field=models.FileField(upload_to='static/uploads/bsms/2024-07-26_13-33-50'),
        ),
    ]
