# Generated by Django 5.1.4 on 2025-04-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0032_alter_bulksms_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulksms',
            name='file',
            field=models.FileField(upload_to='static/uploads/bsms/2025-04-18_09-29-46'),
        ),
    ]
