# Generated by Django 4.1.6 on 2024-09-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0044_alter_bulksms_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailqueues',
            name='mail_key',
            field=models.CharField(default=1, max_length=65),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bulksms',
            name='file',
            field=models.FileField(upload_to='static/uploads/bsms/2024-09-09_11-41-05'),
        ),
    ]
