# Generated by Django 4.1.6 on 2024-09-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0045_mailqueues_mail_key_alter_bulksms_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulksms',
            name='file',
            field=models.FileField(upload_to='static/uploads/bsms/2024-09-09_11-45-03'),
        ),
        migrations.AlterField(
            model_name='mailqueues',
            name='mail_key',
            field=models.CharField(max_length=65, unique=True),
        ),
    ]
