# Generated by Django 5.1.4 on 2025-04-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0046_alter_bulksms_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulksms',
            name='file',
            field=models.FileField(upload_to='static/uploads/bsms/2025-04-23_13-28-08'),
        ),
    ]
