# Generated by Django 4.1.6 on 2024-09-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0046_alter_bulksms_file_alter_mailqueues_mail_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulksms',
            name='file',
            field=models.FileField(upload_to='static/uploads/bsms/2024-09-11_11-17-37'),
        ),
    ]
