# Generated by Django 4.1.6 on 2024-09-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0053_alter_bulksms_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulksms',
            name='file',
            field=models.FileField(upload_to='static/uploads/bsms/2024-09-16_10-37-07'),
        ),
    ]
