# Generated by Django 4.1.6 on 2024-08-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='is_open',
        ),
    ]
