# Generated by Django 4.1.6 on 2024-08-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_followup_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
