# Generated by Django 4.1.6 on 2024-08-16 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_followup_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
