# Generated by Django 4.1.6 on 2024-08-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_logs_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='created_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='logs',
            name='entry_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
