# Generated by Django 4.1.6 on 2024-08-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_logs_created_time_alter_logs_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='created_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='logs',
            name='created_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
