# Generated by Django 4.1.6 on 2024-08-16 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_alter_bulksms_file'),
        ('crm', '0006_alter_logs_created_date_alter_logs_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.geocity'),
        ),
        migrations.AddField(
            model_name='logs',
            name='suburb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.geocitysub'),
        ),
    ]
