# Generated by Django 4.1.6 on 2024-08-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_logs_city_logs_suburb'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
