# Generated by Django 4.1.6 on 2024-08-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_logs_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='google_sync',
            field=models.BooleanField(default=False),
        ),
    ]
