# Generated by Django 4.1.6 on 2024-08-28 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_logs_google_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.logs'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
