# Generated by Django 4.1.6 on 2024-08-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_followup_log_alter_logs_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='validity',
            field=models.IntegerField(default=99),
        ),
    ]
