# Generated by Django 4.1.6 on 2024-08-30 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_logs_validity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogValidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=255)),
                ('is_valid', models.BooleanField(default=False)),
                ('log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.logs')),
            ],
        ),
    ]
