# Generated by Django 4.1.6 on 2024-09-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0002_servicedocument_created_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceDocument',
        ),
    ]
