# Generated by Django 4.1.6 on 2024-09-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0004_servicedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedocument',
            name='document',
            field=models.FileField(upload_to='static/documents/'),
        ),
    ]
