# Generated by Django 4.1.6 on 2024-07-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_alter_products_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_id', models.CharField(max_length=3)),
                ('prod_id', models.CharField(max_length=20)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=60)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('loc_id', 'prod_id')},
            },
        ),
    ]
