# Generated by Django 4.1.6 on 2024-07-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0003_rawstock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rawstock',
            unique_together=set(),
        ),
    ]
