# Generated by Django 4.1.6 on 2024-08-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0004_alter_rawstock_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButcheryLiveTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField()),
                ('bill_ref', models.CharField(max_length=200)),
                ('barcode', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('time', models.TimeField()),
            ],
            options={
                'unique_together': {('bill_ref', 'barcode', 'quantity')},
            },
        ),
    ]
