# Generated by Django 4.1.6 on 2024-08-16 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_alter_bulksms_file'),
        ('retail', '0005_butcherylivetransactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButchSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_checked', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.locations')),
            ],
        ),
        migrations.AddField(
            model_name='butcherylivetransactions',
            name='butch_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retail.butchsales'),
        ),
    ]
