# Generated by Django 4.1.6 on 2024-08-19 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_alter_bulksms_file'),
        ('retail', '0006_butchsales_butcherylivetransactions_butch_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockToSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=20)),
                ('barcode', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('last_transfer_entry', models.CharField(max_length=20)),
                ('last_transfer_date', models.CharField(max_length=20)),
                ('last_transfer_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sold_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('percentage_sold', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('healthy', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.locations')),
            ],
            options={
                'unique_together': {('location', 'item_code')},
            },
        ),
    ]
