# Generated by Django 4.1.6 on 2024-08-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0007_stocktosend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktosend',
            name='barcode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stocktosend',
            name='item_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stocktosend',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
