# Generated by Django 4.1.6 on 2024-08-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0008_alter_stocktosend_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butcherylivetransactions',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='butchsales',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
