# Generated by Django 4.1.6 on 2024-08-21 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0027_alter_bulksms_file'),
        ('retail', '0009_alter_butcherylivetransactions_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranHd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.CharField(max_length=10, unique=True)),
                ('entry_date', models.DateTimeField()),
                ('remarks', models.TextField()),
                ('tot_amt', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('tot_retail', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('user', models.TextField()),
                ('loc_fr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc_fr', to='admin_panel.locations')),
                ('loc_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loc_to', to='admin_panel.locations')),
            ],
        ),
        migrations.CreateModel(
            name='TranTr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('barcode', models.CharField(max_length=20)),
                ('item_code', models.CharField(max_length=20)),
                ('item_descr', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('packing', models.CharField(max_length=20)),
                ('pack_qty', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('total_qty', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.tranhd')),
            ],
        ),
    ]
