# Generated by Django 4.1.6 on 2024-08-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0010_tranhd_trantr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tranhd',
            old_name='remarks',
            new_name='remark',
        ),
        migrations.RenameField(
            model_name='tranhd',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='trantr',
            unique_together={('transfer', 'line_no')},
        ),
    ]
