# Generated by Django 4.1.6 on 2024-08-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0011_rename_remarks_tranhd_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranhd',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
