# Generated by Django 4.1.6 on 2024-08-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0012_alter_tranhd_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktosend',
            name='cust_sold',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
