# Generated by Django 4.1.6 on 2024-08-22 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0013_stocktosend_cust_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boltitems',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='boltitems',
            name='group',
        ),
        migrations.RemoveField(
            model_name='boltitems',
            name='inv_price',
        ),
        migrations.RemoveField(
            model_name='boltitems',
            name='item_des',
        ),
        migrations.RemoveField(
            model_name='boltitems',
            name='price',
        ),
        migrations.RemoveField(
            model_name='boltitems',
            name='price_diff',
        ),
        migrations.AddField(
            model_name='boltitems',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='retail.products'),
        ),
    ]
