# Generated by Django 4.1.6 on 2024-08-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0014_remove_boltitems_barcode_remove_boltitems_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boltitems',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
