# Generated by Django 4.1.6 on 2024-08-22 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0015_boltitems_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boltitems',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='retail.products'),
        ),
    ]
