# Generated by Django 4.1.6 on 2024-08-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0016_alter_boltitems_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=60),
        ),
    ]
