# Generated by Django 4.1.6 on 2024-08-23 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0036_alter_bulksms_file'),
        ('retail', '0017_alter_products_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField()),
                ('tran_time', models.TimeField()),
                ('line_no', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('bill_ref', models.CharField(max_length=200)),
                ('barcode', models.CharField(max_length=20)),
                ('item_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('tran_qty', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('tran_amt', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.locations')),
            ],
            options={
                'unique_together': {('location', 'bill_date', 'tran_time', 'bill_ref', 'item_code', 'tran_qty')},
            },
        ),
    ]
