# Generated by Django 4.1.6 on 2024-08-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0018_retailsales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktosend',
            name='cust_sold',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocktosend',
            name='last_transfer_quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocktosend',
            name='percentage_sold',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocktosend',
            name='sold_quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
