# Generated by Django 5.1.4 on 2025-04-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscenter', '0006_alter_app_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='file',
            field=models.FileField(upload_to='static/uploads/apps/2025-04-08_17-22-12'),
        ),
    ]
