# Generated by Django 5.1.4 on 2025-04-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscenter', '0019_alter_app_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='file',
            field=models.FileField(upload_to='static/uploads/apps/2025-04-12_18-10-33'),
        ),
    ]
