# Generated by Django 4.1.6 on 2024-08-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscenter', '0030_alter_app_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='file',
            field=models.FileField(upload_to='static/uploads/apps/2024-08-22_15-05-52'),
        ),
    ]
