# Generated by Django 4.1.6 on 2024-09-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscenter', '0040_alter_app_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='file',
            field=models.FileField(upload_to='static/uploads/apps/2024-09-04_17-08-30'),
        ),
    ]
