# Generated by Django 5.1.4 on 2025-04-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appscenter', '0060_alter_app_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='file',
            field=models.FileField(upload_to='static/uploads/apps/2025-04-25_15-15-29'),
        ),
    ]
